# Generated by Django 3.1.5 on 2021-01-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('downloads', models.IntegerField(default=0)),
                ('upload_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
