# Generated by Django 3.1.5 on 2021-01-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='titel',
            new_name='title',
        ),
    ]
