# Generated by Django 3.1.5 on 2021-01-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20210120_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(default=None, upload_to='artworks'),
        ),
    ]
